before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: k2Pfif46YydWw0zlotY8fO/Q7BXP0iLdc8hqAnbBXSZyCcjxEfVJwzqqksg/J4zOiMGwT4eB1jcODz4vbMjGDTk+lAZLg7DqyYyPOLLl0pTtHNc6VMQCOdNrU8rGxKqocTf916zlrZUP7WNg8rXymG3hh7gOLYvdQuzvsVchhTG9aVkNljKr6zhArGKR7xZEeuszOVb3Ki9r8gMy2M4crSHeKCIXp20uX1MQgy2NYp2BOJ2imrk57eSLr1LSnvazACBf5HtrY/WH8fi0WGnVrqC1EnF2aaZpIkTvMZJ9wTJAMT3dN5turBgtP+WW+Ia371h1NH5D4/ksOKwywnfZIvEyHKWgJDo6cZ2pP1w+KMC0LXa5mnhjLd/SIAPnDfGi2TSDQIH5p6wOpvrUIzIIoyTv0qe9RfDvP0xJtwJl28EGwCBoS5zT6m21mAwNnEnJ0mYUFVI5f/EGAyvoP4DPIt2UlcjDFX7FF+sfIDLlLfyJgO56HApQBYHA9YWHTTlFtjSpqLORMvbBFZ+qBkGP+a+P5d/4U2nFLnITeFQGdflKvsILDk+rLLe86igyPi7NQNh4jeajheJ6SoP2NKAhvRXkbnA0t9Y24cN6NYJwx1aeo0M1pLv8+KBf4eDUl+F2agqdERChWGlb6xLD5eZyNEhDcEMT/W0JBnHQr2jMgUM= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
